### ISSUE TITLE
panel.vue // 修复：同时这个节点信息

### ISSUE THREAD

**Issue by hubobbb** [BiaoChengLiu/easy-flow#5]
...
deleteNode(nodeId) {
          this.$confirm('确定要删除节点' + nodeId + '?', '提示', {
            confirmButtonText: '确定',
            cancelButtonText: '取消',
            type: 'warning',
            closeOnClickModal: false
          }).then(() => {
            this.data.nodeList = this.data.nodeList.filter(function (node) {
              if (node.id === nodeId) {
                console.log('deleteNode node', node)
                node.show = false 
                return false // 修复：同时这个节点信息
              } else {
                return true
              }
            })
....

**Comment by BiaoChengLiu** [comment]
不太明白你的意思
